# https://pr-agent-docs.codium.ai/
# https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml

[config]
ignore_pr_labels = ['dependencies']
model="gpt-4o-2024-08-06"
model_turbo="gpt-4o-2024-08-06"
fallback_models=["gpt-4o-2024-08-06"]

[pr_description]
publish_labels = false
generate_ai_title = true

[pr_reviewer]
enable_review_labels_effort = false
require_can_be_split_review = true

[pr_code_suggestions]
commitable_code_suggestions = true